include:
  - compose/infra/compose.yml
  - compose/immich/compose.yml
  - compose/apps/compose.yml
  - compose/samba/compose.yml

networks:
  wg-easy:
    name: wg-easy
    ipam:
      config:
        - subnet: 10.10.0.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
