services:
  headscale:
    image: docker.io/headscale/headscale:latest
    restart: unless-stopped
    container_name: headscale
    read_only: true
    tmpfs:
      - /var/run/headscale
    volumes:
      - ./config.yml:/etc/headscale/config.yaml:ro
      - ./acl.json:/etc/headscale/acl.json:ro
      - ./headscale-lib:/var/lib/headscale
    networks:
      - proxy
    command: serve
    healthcheck:
        test: ["CMD", "headscale", "health"]

  caddy:
    build:
      context: .
      dockerfile: caddy.dockerfile
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8443:8443"
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    networks:
      proxy:


volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    name: proxy
