[global]
refresh=2

[outputs]
max_processes_display=25
webui_allowed_hosts=perf.clsn.fr,localhost,127.0.0.1

[network]
# Hide loopback
hide=^lo$

[diskio]
# Hide Snap loop devices and partitions
hide=^loop.*$,^ram.*$,.*[0-9]$

[fs]
# Only show the host root and data filesystem
show=^/rootfs$,^/rootfs/data$

[sensors]
disable=False
# Hide bogus motherboard sensors
hide=AUXTIN0,AUXTIN1,AUXTIN2,AUXTIN3,SYSTIN,PCH_CHIP_CPU_MAX_TEMP,PCH_CHIP_TEMP,PCH_CPU_TEMP,PCH_DIM0_TEMP,PCH_MCH_TEMP


